#!/bin/sh

hdmimode=720p60Hz

for arg in $(cat /proc/cmdline); do
  case ${arg} in
    hdmitx=*)
      hdmitx="${arg#*=}"
      ;;
    hdmimode=*)
      hdmimode=${arg#*=}
      ;;
  esac
done

# Force enable CEC if configuration parameter not present or empty
if [ -z "$hdmitx" ]; then
  echo 0xf > /sys/class/amhdmitx/amhdmitx0/cec_config
fi

# Set framebuffer geometry to match the resolution
case $hdmimode in
  480*)            export X=720  Y=480  ;;
  576*)            export X=720  Y=576  ;;
  720p*)           export X=1280 Y=720  ;;
  1080*)           export X=1920 Y=1080 ;;
  2160p*)          export X=3840 Y=2160 ;;
  smpte24hz*)      export X=3840 Y=2160 ;;
esac

M="0 0 $(($X - 1)) $(($Y - 1))"
Y_VIRT=$(($Y * 2))
fbset -fb /dev/fb0 -g $X $Y $X $Y_VIRT 32
fbset -fb /dev/fb1 -g 32 32 32 32 32
echo $hdmimode > /sys/class/display/mode
echo 0 > /sys/class/graphics/fb0/free_scale
echo 1 > /sys/class/graphics/fb0/freescale_mode
echo $M > /sys/class/graphics/fb0/free_scale_axis
echo $M > /sys/class/graphics/fb0/window_axis
echo 0 > /sys/class/graphics/fb1/free_scale
echo 1 > /sys/class/video/disable_video

# Include deinterlacer into default VFM map
echo rm default > /sys/class/vfm/map
echo add default decoder ppmgr deinterlace amvideo > /sys/class/vfm/map

# Enable framebuffer device
echo 0 > /sys/class/graphics/fb0/blank

# Blank fb1 to prevent static noise
echo 1 > /sys/class/graphics/fb1/blank

for part in /sys/block/*/queue/add_random; do
  echo 0 > "$part"
done

# Fix HEVC playback
echo 16 > /sys/module/amvdec_h265/parameters/dynamic_buf_num_margin
