#!/bin/sh

hdmimode=1080p60hz

for arg in $(cat /proc/cmdline); do
  case ${arg} in
    hdmimode=*)
      hdmimode=${arg#*=}
      ;;
    bootfromsd)
      bootfromsd=1
      ;;
    bootfromusb)
      bootfromusb=1
      ;;
    BOOT_IMAGE=*)
      BOOT_IMAGE=${arg#*=}
      ;;
    boot=*)
      boot=${arg#*=}
      ;;
    disk=*)
      disk=${arg#*=}
      ;;
  esac
done

# Add information where to run LibreELEC from
if [ -z "$BOOT_IMAGE" -o -z "$boot" -o -z "$disk" ]; then
  cmdline=$(cat /proc/cmdline)
  if [ -n "$bootfromsd" ]; then
    cmdline="$cmdline BOOT_IMAGE=kernel.img boot=/dev/mmcblk0p1 disk=/dev/mmcblk0p2"
  elif [ -n "$bootfromusb" ]; then
    cmdline="$cmdline BOOT_IMAGE=kernel.img boot=LABEL=BOOT disk=LABEL=DISK"
  else
    cmdline="$cmdline BOOT_IMAGE=/dev/boot boot=/dev/system disk=/dev/data"
  fi
  echo "$cmdline" > /proc/cmdline
fi

# Set framebuffer geometry to match the resolution
case $hdmimode in
  480*)            X=720  Y=480  ;;
  576*)            X=720  Y=576  ;;
  720p*)           X=1280 Y=720  ;;
  *)               X=1920 Y=1080 ;;
esac

fbset -fb /dev/fb0 -g $X $Y 1920 2160 32
fbset -fb /dev/fb1 -g 32 32 32 32 32
# echo $hdmimode > /sys/class/display/mode
echo 0 > /sys/class/graphics/fb0/free_scale
echo 0 > /sys/class/graphics/fb1/free_scale
echo 1 > /sys/class/video/disable_video

# Enable scaling for 4K output
case $hdmimode in
  4k*|smpte*|2160*)
    echo 0 0 1919 1079 > /sys/class/graphics/fb0/free_scale_axis
    echo 0 0 3839 2159 > /sys/class/graphics/fb0/window_axis
    echo 1920 > /sys/class/graphics/fb0/scale_width
    echo 1080 > /sys/class/graphics/fb0/scale_height
    echo 0x10001 > /sys/class/graphics/fb0/free_scale
  ;;
esac

# Include deinterlacer into default VFM map
echo rm default > /sys/class/vfm/map
echo add default decoder ppmgr deinterlace amvideo > /sys/class/vfm/map

# Enable framebuffer device
echo 0 > /sys/class/graphics/fb0/blank

# Blank fb1 to prevent static noise
echo 1 > /sys/class/graphics/fb1/blank

for part in /sys/block/*/queue/add_random; do
  echo 0 > "$part"
done
