#!/bin/sh

hdmimode=1080p60Hz

for arg in $(cat /proc/cmdline); do
  case ${arg} in
    hdmimode=*)
      hdmimode=${arg#*=}
      ;;
  esac
done

# Set framebuffer geometry to match the resolution
case $hdmimode in
  480*)            export X=720  Y=480  ;;
  576*)            export X=720  Y=576  ;;
  720p*)           export X=1280 Y=720  ;;
  1080*)           export X=1920 Y=1080 ;;
  2160p*)          export X=3840 Y=2160 ;;
  smpte24hz*)      export X=3840 Y=2160 ;;
esac

# Get max supported display resolution by hdmi device
maxRes=$(tail -n1 /sys/class/amhdmitx/amhdmitx0/disp_cap | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//');
if [ -z "$maxRes" ]; then
  maxRes="$hdmimode";
fi
case "$maxRes" in
  480*)                export X_VIRT=720  Y_VIRT=960  ;;
  576*)                export X_VIRT=720  Y_VIRT=1152 ;;
  720*)                export X_VIRT=1280 Y_VIRT=1440 ;;
  1080*)               export X_VIRT=1920 Y_VIRT=2160 ;;
  4k2k*hz|2160p*)      export X_VIRT=3840 Y_VIRT=4320 ;;
  4k2ksmpte|smpte24hz) export X_VIRT=4096 Y_VIRT=4320 ;;
esac

M="0 0 $(($X - 1)) $(($Y - 1))"
fbset -fb /dev/fb0 -g $X $Y $X_VIRT $Y_VIRT 32
fbset -fb /dev/fb1 -g 32 32 32 32 32
echo $hdmimode > /sys/class/display/mode
echo 0 > /sys/class/graphics/fb0/free_scale
echo 1 > /sys/class/graphics/fb0/freescale_mode
echo $M > /sys/class/graphics/fb0/free_scale_axis
echo $M > /sys/class/graphics/fb0/window_axis
echo 0 > /sys/class/graphics/fb1/free_scale
echo 1 > /sys/class/video/disable_video

# Include deinterlacer into default VFM map
echo rm default > /sys/class/vfm/map
echo add default decoder ppmgr deinterlace amvideo > /sys/class/vfm/map

# Enable framebuffer device
echo 0 > /sys/class/graphics/fb0/blank

# Blank fb1 to prevent static noise
echo 1 > /sys/class/graphics/fb1/blank

for part in /sys/block/*/queue/add_random; do
  echo 0 > "$part"
done

# Tweak HEVC playback
echo 8 >  /sys/module/amvdec_h265/parameters/buffer_mode
echo 16 > /sys/module/amvdec_h265/parameters/dynamic_buf_num_margin
echo 1 >  /sys/module/amvdec_h265/parameters/use_cma
